project_name: "klasifikator-api"
version: "1.0.0"

inference:
  model_checkpoint_dir: "experiments/model_wandb_20260115_213548"
  host: "0.0.0.0"
  port: 8000
  enable_cors: true

  top_k: 5  
  batch_size: 32 
